# Generated by Django 5.1.4 on 2025-01-08 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=100, null=True)),
                ("logo", models.ImageField(upload_to="logo/")),
                ("purse_remaining", models.IntegerField(default=1000)),
                ("manager", models.CharField(max_length=100)),
                ("owner", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("card_image", models.ImageField(upload_to="player_cards/")),
                (
                    "base_price",
                    models.DecimalField(decimal_places=2, default=20, max_digits=10),
                ),
                ("year", models.IntegerField()),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="auction.team",
                    ),
                ),
            ],
        ),
    ]
