# Generated by Django 5.1.4 on 2025-01-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="shown",
            field=models.BooleanField(default=False),
        ),
    ]
